Repository unraid/webgui, pull requests merged in 2025-06, with the labels that each got.

#2226 Backport to 7.0: fix for encryption passphrase sometimes incorrect
  emhttp/plugins/dynamix/ArrayOperation.page
  emhttp/plugins/dynamix/DiskSettings.page
  emhttp/plugins/dynamix/include/Helpers.php
  emhttp/plugins/dynamix/include/KeyUpload.php
  emhttp/plugins/dynamix/include/Wrappers.php
  emhttp/plugins/dynamix/include/update.encryption.php
  emhttp/plugins/dynamix/nchan/device_list
Labels: 7.0

#2229 MAC Address option and ZFS ref link
  emhttp/plugins/dynamix.vm.manager/VMMachines.page
  emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
  emhttp/plugins/dynamix.vm.manager/scripts/VMClone.php
  emhttp/plugins/dynamix/DashStats.page
Labels: 7.2

#2241 More networking fixes
  emhttp/plugins/dynamix/Eth0.page
  emhttp/plugins/dynamix/EthX.page
  etc/rc.d/rc.docker
  etc/rc.d/rc.inet1
  sbin/create_network_ini
  sbin/monitor_interface
Labels: 7.2

#2260 backport: File manager: fix file overwrite on move operation
  emhttp/plugins/dynamix/nchan/file_manager
Labels: 7.1

#2253 style: prevent default swal overflow
  emhttp/plugins/dynamix/styles/jquery.sweetalert.css
Labels: 7.2

#2254 File manager: fix file overwrite on move operation
  emhttp/plugins/dynamix/nchan/file_manager
Labels: 7.2

#2263 fix: SSO options missing on 7.2
  emhttp/plugins/dynamix/include/.login.php
Labels: 7.2

#2265 Fix noVNC missing icons with update base.css
  emhttp/plugins/dynamix.vm.manager/novnc/app/styles/base.css
Labels: 7.2

#2266 Enhance multimonitor support.
  emhttp/plugins/dynamix.vm.manager/include/libvirt.php
  emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
Labels: 7.2

#2264 Feat: Add timer to login screen when cooldown period is active
  emhttp/plugins/dynamix/include/.login.php
Labels: 7.2

#2274 fix: DeviceInfo balance status
  emhttp/plugins/dynamix/DeviceInfo.page
Labels: 7.2

#2275 style: enable horizontal scrolling for legacy content
  emhttp/plugins/dynamix/styles/default-base.css
Labels: 7.2

#2276 fix: boot page update viewport meta tag for responsiveness
  emhttp/plugins/dynamix/include/Boot.php
Labels: 7.2

#2277 fix: update custom banner path in DefaultPageLayout.php
  emhttp/plugins/dynamix/include/DefaultPageLayout.php
Labels: 7.2

#2278 feat: vm responsive layout fallback
  emhttp/plugins/dynamix.vm.manager/include/VMedit.php
  emhttp/plugins/dynamix.vm.manager/styles/edit.css
  emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
  emhttp/plugins/dynamix/styles/default-base.css
Labels: 7.2

#2279 fix: display settings listing height responsive regression
  emhttp/plugins/dynamix.docker.manager/DockerContainers.page
  emhttp/plugins/dynamix.vm.manager/VMMachines.page
  emhttp/plugins/dynamix/PageMap.page
  emhttp/plugins/dynamix/Processes.page
  emhttp/plugins/dynamix/Syslog.page
  emhttp/plugins/dynamix/Vars.page
  emhttp/plugins/dynamix/include/DefaultPageLayout/BodyInlineJS.php
  emhttp/plugins/dynamix/include/DefaultPageLayout/HeadInlineJS.php
  emhttp/plugins/dynamix/sheets/Syslog.css
Labels: 7.2

#2280 feat: Remove support for ipv6.hash.myunraid.net URLs
  emhttp/plugins/dynamix/ManagementAccess.page
  etc/rc.d/rc.nginx
Labels: 7.2

#2281 fix: parse_plugin_cfg(): better handling of corrupt ini files
  emhttp/plugins/dynamix/include/Report.php
  emhttp/plugins/dynamix/include/Wrappers.php
Labels: 7.2

#2283 Fix: PCI Changes
  emhttp/plugins/dynamix/include/PCIUpdate.php
  sbin/savepcidata
Labels: 7.2
