Repository unraid/webgui, pull requests merged in 2025-05, with the labels that each got.

#2177 XML Icon change fix.
  emhttp/plugins/dynamix.vm.manager/include/VMedit.php
  emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
Labels: 7.1

#2180 fix: diagnostics: prevent warnings for non-existent files, take 2
  emhttp/plugins/dynamix/scripts/diagnostics
Labels: 7.1

#2181 Refactor: Only reload Main/Dash on visibility if Live Updates disabled
  emhttp/plugins/dynamix/include/DefaultPageLayout.php
Labels: 7.1

#2132 refactor: abstract out styles from DefaultPageLayout
  emhttp/plugins/dynamix.vm.manager/VMSettings.page
  emhttp/plugins/dynamix/include/.login.php
  emhttp/plugins/dynamix/include/.set-password.php
  emhttp/plugins/dynamix/include/Boot.php
  emhttp/plugins/dynamix/include/DefaultPageLayout.php
  emhttp/plugins/dynamix/include/PageBuilder.php
  emhttp/plugins/dynamix/include/ThemeHelper.php
  emhttp/plugins/dynamix/styles/default-base.css
  emhttp/plugins/dynamix/styles/themes/README.md
  emhttp/plugins/dynamix/styles/themes/azure.css
  emhttp/plugins/dynamix/styles/themes/black.css
  emhttp/plugins/dynamix/styles/themes/gray.css
  emhttp/plugins/dynamix/styles/themes/white.css
Labels: 7.2

#2133 refactor: abstract out JS scripts from DefaultPageLayout
  emhttp/plugins/dynamix/include/DefaultPageLayout.php
  emhttp/plugins/dynamix/include/DefaultPageLayout/BodyInlineJS.php
  emhttp/plugins/dynamix/include/DefaultPageLayout/HeadInlineJS.php
Labels: 7.2

#2134 refactor: organize nchan usage in DefaultPageLayout
  emhttp/plugins/dynamix/include/DefaultPageLayout.php
Labels: 7.2

#2135 refactor: DefaultPageLayout header & navigation template includes
  emhttp/plugins/dynamix/include/DefaultPageLayout.php
  emhttp/plugins/dynamix/include/DefaultPageLayout/Header.php
  emhttp/plugins/dynamix/include/DefaultPageLayout/Navigation/Main.php
  emhttp/plugins/dynamix/styles/default-base.css
Labels: 7.2

#2136 refactor: abstract misc global elements from DefaultPageLayout.php into MiscElements.php
  emhttp/plugins/dynamix/include/DefaultPageLayout.php
  emhttp/plugins/dynamix/include/DefaultPageLayout/MiscElements.php
Labels: 7.2

#2139 refactor: abstract main content logic into MainContent.php
  emhttp/plugins/dynamix/include/DefaultPageLayout.php
  emhttp/plugins/dynamix/include/DefaultPageLayout/MainContent.php
  emhttp/plugins/dynamix/include/PageBuilder.php
Labels: 7.2

#2068 7.x Save PCI Data.
  emhttp/plugins/dynamix.vm.manager/include/VMMachines.php
  emhttp/plugins/dynamix.vm.manager/include/libvirt.php
  emhttp/plugins/dynamix.vm.manager/javascript/vmmanager.js
  emhttp/plugins/dynamix.vm.manager/scripts/pcicheck.php
  emhttp/plugins/dynamix/SysDevs.page
  emhttp/plugins/dynamix/include/DashboardApps.php
  emhttp/plugins/dynamix/include/Helpers.php
  emhttp/plugins/dynamix/include/PCIUpdate.php
  emhttp/plugins/dynamix/include/SysDevs.php
  etc/rc.d/rc.6
  sbin/qemu
  sbin/savepcidata
Labels: 7.2

#2178 feat: add force checkbox to plugin install page
  emhttp/plugins/dynamix.plugin.manager/PluginInstall.page
Labels: 7.2

#2149 7.x Initial Commit for Virtual sound cards.
  emhttp/plugins/dynamix.vm.manager/include/libvirt.php
  emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
  emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
Labels: 7.2

#2141 7.x Intel processor core types
  emhttp/plugins/dynamix.vm.manager/VMMachines.page
  emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
  emhttp/plugins/dynamix/CPUvms.page
  emhttp/plugins/dynamix/DashStats.page
  emhttp/plugins/dynamix/include/CPUset.php
  emhttp/plugins/dynamix/include/Helpers.php
  emhttp/plugins/dynamix/include/SysDevs.php
Labels: 7.2

#2186 Miscellanous network fixes and improvements
  emhttp/plugins/dynamix/Eth0.page
  emhttp/plugins/dynamix/EthX.page
  emhttp/plugins/dynamix/include/RoutingTable.php
  emhttp/plugins/dynamix/scripts/reload_services
  emhttp/plugins/dynamix/scripts/update_services
  etc/rc.d/rc.docker
  etc/rc.d/rc.inet1
  etc/rc.d/rc.library.source
  etc/rc.d/rc.local
  etc/rc.d/rc.nginx
  etc/rc.d/rc.wireless
  sbin/create_network_ini
  sbin/monitor_interface
Labels: 7.2

#2189 feat: add tweaks for the Unraid API
  emhttp/auth-request.php
  emhttp/plugins/dynamix/LogViewer.page
  emhttp/plugins/dynamix/include/DefaultPageLayout.php
  emhttp/plugins/dynamix/include/DefaultPageLayout/BodyInlineJS.php
  emhttp/plugins/dynamix/include/DefaultPageLayout/GUIModeSessionFix.php
  emhttp/plugins/dynamix/include/DefaultPageLayout/HeadInlineJS.php
  emhttp/plugins/dynamix/include/DefaultPageLayout/Header.php
  emhttp/plugins/dynamix/include/DefaultPageLayout/ToastSetup.php
  emhttp/plugins/dynamix/include/JSCache.php
  emhttp/plugins/dynamix/javascript/dynamix.js
  emhttp/plugins/dynamix/styles/default-dynamix.css
Labels: 7.2

#2190 feat: enable SSO on 7.2 with the Unraid API
  emhttp/plugins/dynamix/include/.login.php
Labels: 7.2

#2193 feat: safe mode go script handling
  emhttp/plugins/dynamix/scripts/diagnostics
  etc/rc.d/rc.local
Labels: 7.2

#2195 monitor_nchan: fix non-numeral results in comparison line
  sbin/create_network_ini
  sbin/monitor_nchan
Labels: 7.2

#2196 Add pci checks in qemu
  emhttp/plugins/dynamix.vm.manager/scripts/pcicheck.php
  sbin/qemu
Labels: 7.2

#2201 Update GUIModeSessionFix.php
  emhttp/plugins/dynamix/include/DefaultPageLayout/GUIModeSessionFix.php
Labels: 7.2

#2202 fix: blob links shouldn't be external
  emhttp/plugins/dynamix/include/DefaultPageLayout/BodyInlineJS.php
Labels: 7.2

#2203 feat: responsive improvements
  emhttp/plugins/dynamix.apcupsd/UPSdetails.page
  emhttp/plugins/dynamix.docker.manager/DockerSettings.page
  emhttp/plugins/dynamix.docker.manager/include/CreateDocker.php
  emhttp/plugins/dynamix.docker.manager/sheets/AddContainer.css
  emhttp/plugins/dynamix.docker.manager/sheets/DockerSettings.css
  emhttp/plugins/dynamix.vm.manager/VMSettings.page
  emhttp/plugins/dynamix.vm.manager/sheets/VMSettings.css
  emhttp/plugins/dynamix/CPUisol.page
  emhttp/plugins/dynamix/CPUpin.page
  emhttp/plugins/dynamix/CPUvms.page
  emhttp/plugins/dynamix/DeviceInfo.page
  emhttp/plugins/dynamix/DiskSettings.page
  emhttp/plugins/dynamix/Eth0.page
  emhttp/plugins/dynamix/EthX.page
  emhttp/plugins/dynamix/NetworkExtra.page
  emhttp/plugins/dynamix/NetworkRules.page
  emhttp/plugins/dynamix/ParityCheck.page
  emhttp/plugins/dynamix/RoutingTable.page
  emhttp/plugins/dynamix/Syslinux.page
  emhttp/plugins/dynamix/Syslog.page
  emhttp/plugins/dynamix/UserAdd.page
  emhttp/plugins/dynamix/UserEdit.page
  emhttp/plugins/dynamix/Wireless.page
  emhttp/plugins/dynamix/include/DefaultPageLayout/HeadInlineJS.php
  emhttp/plugins/dynamix/include/Wireless.php
  emhttp/plugins/dynamix/sheets/Eth0.css
  emhttp/plugins/dynamix/sheets/NetworkExtra.css
  emhttp/plugins/dynamix/sheets/NetworkRules.css
  emhttp/plugins/dynamix/sheets/Syslog.css
  emhttp/plugins/dynamix/sheets/Wireless.css
  emhttp/plugins/dynamix/styles/default-base.css
  emhttp/plugins/dynamix/styles/default-dynamix.css
Labels: 7.2

#2204 feat: remove NotificationsArchive page and related files
  emhttp/plugins/dynamix/NotificationsArchive.page
  emhttp/plugins/dynamix/include/DefaultPageLayout/BodyInlineJS.php
  emhttp/plugins/dynamix/include/DefaultPageLayout/HeadInlineJS.php
  emhttp/plugins/dynamix/include/DefaultPageLayout/Navigation/Main.php
  emhttp/plugins/dynamix/include/NotificationsArchive.php
  emhttp/plugins/dynamix/sheets/NotificationsArchive.css
Labels: 7.2

#2205 Miscellaneous fixes
  emhttp/plugins/dynamix/BrowseButton.page
  emhttp/plugins/dynamix/ParityCheck.page
Labels: 7.2

#2208 Fix: Re-enable smart test buttons after completion of test
  emhttp/plugins/dynamix/Selftest.page
Labels: 7.2

#2210 Feat: Terminal - Add button to manually open if popup blocked
  emhttp/plugins/dynamix/Terminal.page
  emhttp/plugins/dynamix/include/DefaultPageLayout/HeadInlineJS.php
Labels: 7.2

#2209 Miscellaneous fixes
  emhttp/plugins/dynamix.docker.manager/DockerSettings.page
  emhttp/plugins/dynamix/Eth0.page
  emhttp/plugins/dynamix/EthX.page
Labels: 7.2

#2211 feat: responsive improvements rd. 2
  emhttp/plugins/dynamix.gui.search/gui_search.page
  emhttp/plugins/dynamix.gui.search/sheets/gui_search.css
  emhttp/plugins/dynamix.my.servers/unraid-components/nuxt/_nuxt/unraid-components-BvEqdEb_.css
  emhttp/plugins/dynamix.my.servers/unraid-components/nuxt/_nuxt/unraid-components.client-Chq1f4tv.js
  emhttp/plugins/dynamix.my.servers/unraid-components/nuxt/manifest.json
  emhttp/plugins/dynamix.my.servers/unraid-components/uui/register.D9MKs8Co.js
  emhttp/plugins/dynamix.my.servers/unraid-components/uui/register.D9MKs8Co.js.map
  emhttp/plugins/dynamix.my.servers/unraid-components/uui/ui.CaW9jS_X.css
  emhttp/plugins/dynamix.my.servers/unraid-components/uui/ui.manifest.json
  emhttp/plugins/dynamix/Disk.page
  emhttp/plugins/dynamix/Eth0.page
  emhttp/plugins/dynamix/Favorites.page
  emhttp/plugins/dynamix/Flash.page
  emhttp/plugins/dynamix/MyFavorites.page
  emhttp/plugins/dynamix/NotificationAgents.page
  emhttp/plugins/dynamix/Share.page
  emhttp/plugins/dynamix/include/DefaultPageLayout/MainContent.php
  emhttp/plugins/dynamix/include/Helpers.php
  emhttp/plugins/dynamix/sheets/WG0.css
  emhttp/plugins/dynamix/styles/default-base.css
  emhttp/plugins/dynamix/styles/default-dynamix.css
Labels: 7.2

#2213 Chore: Terminal: Move option placement and change default setting
  emhttp/plugins/dynamix/DisplaySettings.page
  emhttp/plugins/dynamix/Terminal.page
  emhttp/plugins/dynamix/default.cfg
Labels: 7.2

#2215 Encryption: fix passphrase encryption not working in some cases
  emhttp/plugins/dynamix/ArrayOperation.page
  emhttp/plugins/dynamix/DiskSettings.page
  emhttp/plugins/dynamix/include/Helpers.php
  emhttp/plugins/dynamix/include/KeyUpload.php
  emhttp/plugins/dynamix/include/Wrappers.php
  emhttp/plugins/dynamix/include/update.encryption.php
  emhttp/plugins/dynamix/nchan/device_list
  emhttp/plugins/dynamix/scripts/update_services
  sbin/monitor_nchan
Labels: 7.2

#2214 Backport networking fixes to 7.1
  emhttp/plugins/dynamix/Eth0.page
  emhttp/plugins/dynamix/EthX.page
  emhttp/plugins/dynamix/include/RoutingTable.php
  emhttp/plugins/dynamix/scripts/reload_services
  emhttp/plugins/dynamix/scripts/update_services
  etc/rc.d/rc.docker
  etc/rc.d/rc.inet1
  etc/rc.d/rc.library.source
  etc/rc.d/rc.local
  etc/rc.d/rc.nginx
  etc/rc.d/rc.wireless
  sbin/create_network_ini
  sbin/monitor_interface
  sbin/monitor_nchan
Labels: 7.1

#2065 Backport Fix: Disallow HTML within plugin attributes
  emhttp/plugins/dynamix.plugin.manager/scripts/plugin
Labels: 7.0

#2160 Backport: fix: diagnostics: anonymize IPv6 addresses in lsof.txt
  emhttp/plugins/dynamix/scripts/diagnostics
Labels: 7.0

#2217 fix: add ServerState dependency to login page
  emhttp/plugins/dynamix/include/.login.php
Labels: 7.2

#2218 fix: limit pgrep/pkill to host namespace
  emhttp/plugins/dynamix/DateTime.page
  emhttp/plugins/dynamix/include/DashboardApps.php
  emhttp/plugins/dynamix/include/DefaultPageLayout.php
  emhttp/plugins/dynamix/include/ResetTZ.php
  emhttp/plugins/dynamix/scripts/reiserfs_check
  emhttp/plugins/dynamix/scripts/upnp_port
  etc/rc.d/rc.cgroup2unraid
  etc/rc.d/rc.nginx
  etc/rc.d/rc.ntpd
  etc/rc.d/rc.ptpd
  etc/rc.d/rc.wireless
  sbin/emhttp
  sbin/monitor_nchan
Labels: 7.2

#2221 Backport Fix: Revert allow docker context menus above or below
  emhttp/plugins/dynamix.docker.manager/javascript/docker.js
Labels: 7.1
